# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
      - name: Check Job Status status and fail if they are red

        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
        
  deploy:
    needs: built
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
             heroku_api_key: ${{secrets.HEROKU_API_KEY}}
             heroku_app_name: "appnodedearan"
             heroku_email: "doradoaranzazu@gmail.com"
