# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      
  deploy:
  
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - uses: akhileshns/heroku-deploy@v3.16.16 # This is the action
           with:
             heroku_api_key: ${{secrets.HEROKU_API_KEY}}
             heroku_app_name: "appnodedearan"
             heroku_email: "doradoaranzazu@gmail.com"
